/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as WaitlistRouteImport } from './app/waitlist'
import { Route as AnalyzeRouteImport } from './app/analyze'
import { Route as IndexRouteImport } from './app/index'
import { Route as OnboardingIndexRouteImport } from './app/onboarding/index'
import { Route as AuthIndexRouteImport } from './app/auth/index'
import { Route as UsernameIndexRouteImport } from './app/$username/index'
import { Route as OnboardingConnectRouteImport } from './app/onboarding/connect'
import { Route as AnalyzeChatRouteImport } from './app/analyze.chat'
import { Route as UsernameTracksRouteImport } from './app/$username/tracks'
import { Route as UsernamePlaylistsRouteImport } from './app/$username/playlists'
import { Route as UsernameCollectionRouteImport } from './app/$username/collection'
import { Route as UsernameSettingsIndexRouteImport } from './app/$username/settings/index'
import { Route as ApiAiChatRouteImport } from './app/api/ai/chat'
import { Route as UsernameSettingsConnectionsRouteImport } from './app/$username/settings/connections'
import { Route as ApiExternalYoutubeSearchRouteImport } from './app/api/external/youtube/search'
import { Route as ApiExternalYoutubeVideoIdRouteImport } from './app/api/external/youtube/$videoId'
import { Route as ApiExternalDiscogsSearchRouteImport } from './app/api/external/discogs/search'
import { Route as ApiExternalDiscogsCollectionRouteImport } from './app/api/external/discogs/collection'
import { Route as ApiAuthDiscogsStatusRouteImport } from './app/api/auth/discogs/status'
import { Route as ApiAuthDiscogsRequestTokenRouteImport } from './app/api/auth/discogs/request-token'
import { Route as ApiAuthDiscogsDisconnectRouteImport } from './app/api/auth/discogs/disconnect'
import { Route as ApiAuthDiscogsCallbackRouteImport } from './app/api/auth/discogs/callback'
import { Route as ApiExternalDiscogsReleaseIdRouteImport } from './app/api/external/discogs/release/$id'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameIndexRoute = UsernameIndexRouteImport.update({
  id: '/$username/',
  path: '/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingConnectRoute = OnboardingConnectRouteImport.update({
  id: '/onboarding/connect',
  path: '/onboarding/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeChatRoute = AnalyzeChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AnalyzeRoute,
} as any)
const UsernameTracksRoute = UsernameTracksRouteImport.update({
  id: '/$username/tracks',
  path: '/$username/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernamePlaylistsRoute = UsernamePlaylistsRouteImport.update({
  id: '/$username/playlists',
  path: '/$username/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameCollectionRoute = UsernameCollectionRouteImport.update({
  id: '/$username/collection',
  path: '/$username/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameSettingsIndexRoute = UsernameSettingsIndexRouteImport.update({
  id: '/$username/settings/',
  path: '/$username/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameSettingsConnectionsRoute =
  UsernameSettingsConnectionsRouteImport.update({
    id: '/$username/settings/connections',
    path: '/$username/settings/connections',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExternalYoutubeSearchRoute =
  ApiExternalYoutubeSearchRouteImport.update({
    id: '/api/external/youtube/search',
    path: '/api/external/youtube/search',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExternalYoutubeVideoIdRoute =
  ApiExternalYoutubeVideoIdRouteImport.update({
    id: '/api/external/youtube/$videoId',
    path: '/api/external/youtube/$videoId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExternalDiscogsSearchRoute =
  ApiExternalDiscogsSearchRouteImport.update({
    id: '/api/external/discogs/search',
    path: '/api/external/discogs/search',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExternalDiscogsCollectionRoute =
  ApiExternalDiscogsCollectionRouteImport.update({
    id: '/api/external/discogs/collection',
    path: '/api/external/discogs/collection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthDiscogsStatusRoute = ApiAuthDiscogsStatusRouteImport.update({
  id: '/api/auth/discogs/status',
  path: '/api/auth/discogs/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscogsRequestTokenRoute =
  ApiAuthDiscogsRequestTokenRouteImport.update({
    id: '/api/auth/discogs/request-token',
    path: '/api/auth/discogs/request-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthDiscogsDisconnectRoute =
  ApiAuthDiscogsDisconnectRouteImport.update({
    id: '/api/auth/discogs/disconnect',
    path: '/api/auth/discogs/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthDiscogsCallbackRoute = ApiAuthDiscogsCallbackRouteImport.update({
  id: '/api/auth/discogs/callback',
  path: '/api/auth/discogs/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExternalDiscogsReleaseIdRoute =
  ApiExternalDiscogsReleaseIdRouteImport.update({
    id: '/api/external/discogs/release/$id',
    path: '/api/external/discogs/release/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRouteWithChildren
  '/waitlist': typeof WaitlistRoute
  '/$username/collection': typeof UsernameCollectionRoute
  '/$username/playlists': typeof UsernamePlaylistsRoute
  '/$username/tracks': typeof UsernameTracksRoute
  '/analyze/chat': typeof AnalyzeChatRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/$username': typeof UsernameIndexRoute
  '/auth': typeof AuthIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/$username/settings/connections': typeof UsernameSettingsConnectionsRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/$username/settings': typeof UsernameSettingsIndexRoute
  '/api/auth/discogs/callback': typeof ApiAuthDiscogsCallbackRoute
  '/api/auth/discogs/disconnect': typeof ApiAuthDiscogsDisconnectRoute
  '/api/auth/discogs/request-token': typeof ApiAuthDiscogsRequestTokenRoute
  '/api/auth/discogs/status': typeof ApiAuthDiscogsStatusRoute
  '/api/external/discogs/collection': typeof ApiExternalDiscogsCollectionRoute
  '/api/external/discogs/search': typeof ApiExternalDiscogsSearchRoute
  '/api/external/youtube/$videoId': typeof ApiExternalYoutubeVideoIdRoute
  '/api/external/youtube/search': typeof ApiExternalYoutubeSearchRoute
  '/api/external/discogs/release/$id': typeof ApiExternalDiscogsReleaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRouteWithChildren
  '/waitlist': typeof WaitlistRoute
  '/$username/collection': typeof UsernameCollectionRoute
  '/$username/playlists': typeof UsernamePlaylistsRoute
  '/$username/tracks': typeof UsernameTracksRoute
  '/analyze/chat': typeof AnalyzeChatRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/$username': typeof UsernameIndexRoute
  '/auth': typeof AuthIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/$username/settings/connections': typeof UsernameSettingsConnectionsRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/$username/settings': typeof UsernameSettingsIndexRoute
  '/api/auth/discogs/callback': typeof ApiAuthDiscogsCallbackRoute
  '/api/auth/discogs/disconnect': typeof ApiAuthDiscogsDisconnectRoute
  '/api/auth/discogs/request-token': typeof ApiAuthDiscogsRequestTokenRoute
  '/api/auth/discogs/status': typeof ApiAuthDiscogsStatusRoute
  '/api/external/discogs/collection': typeof ApiExternalDiscogsCollectionRoute
  '/api/external/discogs/search': typeof ApiExternalDiscogsSearchRoute
  '/api/external/youtube/$videoId': typeof ApiExternalYoutubeVideoIdRoute
  '/api/external/youtube/search': typeof ApiExternalYoutubeSearchRoute
  '/api/external/discogs/release/$id': typeof ApiExternalDiscogsReleaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRouteWithChildren
  '/waitlist': typeof WaitlistRoute
  '/$username/collection': typeof UsernameCollectionRoute
  '/$username/playlists': typeof UsernamePlaylistsRoute
  '/$username/tracks': typeof UsernameTracksRoute
  '/analyze/chat': typeof AnalyzeChatRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/$username/': typeof UsernameIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/$username/settings/connections': typeof UsernameSettingsConnectionsRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/$username/settings/': typeof UsernameSettingsIndexRoute
  '/api/auth/discogs/callback': typeof ApiAuthDiscogsCallbackRoute
  '/api/auth/discogs/disconnect': typeof ApiAuthDiscogsDisconnectRoute
  '/api/auth/discogs/request-token': typeof ApiAuthDiscogsRequestTokenRoute
  '/api/auth/discogs/status': typeof ApiAuthDiscogsStatusRoute
  '/api/external/discogs/collection': typeof ApiExternalDiscogsCollectionRoute
  '/api/external/discogs/search': typeof ApiExternalDiscogsSearchRoute
  '/api/external/youtube/$videoId': typeof ApiExternalYoutubeVideoIdRoute
  '/api/external/youtube/search': typeof ApiExternalYoutubeSearchRoute
  '/api/external/discogs/release/$id': typeof ApiExternalDiscogsReleaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/waitlist'
    | '/$username/collection'
    | '/$username/playlists'
    | '/$username/tracks'
    | '/analyze/chat'
    | '/onboarding/connect'
    | '/$username'
    | '/auth'
    | '/onboarding'
    | '/$username/settings/connections'
    | '/api/ai/chat'
    | '/$username/settings'
    | '/api/auth/discogs/callback'
    | '/api/auth/discogs/disconnect'
    | '/api/auth/discogs/request-token'
    | '/api/auth/discogs/status'
    | '/api/external/discogs/collection'
    | '/api/external/discogs/search'
    | '/api/external/youtube/$videoId'
    | '/api/external/youtube/search'
    | '/api/external/discogs/release/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/waitlist'
    | '/$username/collection'
    | '/$username/playlists'
    | '/$username/tracks'
    | '/analyze/chat'
    | '/onboarding/connect'
    | '/$username'
    | '/auth'
    | '/onboarding'
    | '/$username/settings/connections'
    | '/api/ai/chat'
    | '/$username/settings'
    | '/api/auth/discogs/callback'
    | '/api/auth/discogs/disconnect'
    | '/api/auth/discogs/request-token'
    | '/api/auth/discogs/status'
    | '/api/external/discogs/collection'
    | '/api/external/discogs/search'
    | '/api/external/youtube/$videoId'
    | '/api/external/youtube/search'
    | '/api/external/discogs/release/$id'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/waitlist'
    | '/$username/collection'
    | '/$username/playlists'
    | '/$username/tracks'
    | '/analyze/chat'
    | '/onboarding/connect'
    | '/$username/'
    | '/auth/'
    | '/onboarding/'
    | '/$username/settings/connections'
    | '/api/ai/chat'
    | '/$username/settings/'
    | '/api/auth/discogs/callback'
    | '/api/auth/discogs/disconnect'
    | '/api/auth/discogs/request-token'
    | '/api/auth/discogs/status'
    | '/api/external/discogs/collection'
    | '/api/external/discogs/search'
    | '/api/external/youtube/$videoId'
    | '/api/external/youtube/search'
    | '/api/external/discogs/release/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRouteWithChildren
  WaitlistRoute: typeof WaitlistRoute
  UsernameCollectionRoute: typeof UsernameCollectionRoute
  UsernamePlaylistsRoute: typeof UsernamePlaylistsRoute
  UsernameTracksRoute: typeof UsernameTracksRoute
  OnboardingConnectRoute: typeof OnboardingConnectRoute
  UsernameIndexRoute: typeof UsernameIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  UsernameSettingsConnectionsRoute: typeof UsernameSettingsConnectionsRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  UsernameSettingsIndexRoute: typeof UsernameSettingsIndexRoute
  ApiAuthDiscogsCallbackRoute: typeof ApiAuthDiscogsCallbackRoute
  ApiAuthDiscogsDisconnectRoute: typeof ApiAuthDiscogsDisconnectRoute
  ApiAuthDiscogsRequestTokenRoute: typeof ApiAuthDiscogsRequestTokenRoute
  ApiAuthDiscogsStatusRoute: typeof ApiAuthDiscogsStatusRoute
  ApiExternalDiscogsCollectionRoute: typeof ApiExternalDiscogsCollectionRoute
  ApiExternalDiscogsSearchRoute: typeof ApiExternalDiscogsSearchRoute
  ApiExternalYoutubeVideoIdRoute: typeof ApiExternalYoutubeVideoIdRoute
  ApiExternalYoutubeSearchRoute: typeof ApiExternalYoutubeSearchRoute
  ApiExternalDiscogsReleaseIdRoute: typeof ApiExternalDiscogsReleaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/': {
      id: '/$username/'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/connect': {
      id: '/onboarding/connect'
      path: '/onboarding/connect'
      fullPath: '/onboarding/connect'
      preLoaderRoute: typeof OnboardingConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/chat': {
      id: '/analyze/chat'
      path: '/chat'
      fullPath: '/analyze/chat'
      preLoaderRoute: typeof AnalyzeChatRouteImport
      parentRoute: typeof AnalyzeRoute
    }
    '/$username/tracks': {
      id: '/$username/tracks'
      path: '/$username/tracks'
      fullPath: '/$username/tracks'
      preLoaderRoute: typeof UsernameTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/playlists': {
      id: '/$username/playlists'
      path: '/$username/playlists'
      fullPath: '/$username/playlists'
      preLoaderRoute: typeof UsernamePlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/collection': {
      id: '/$username/collection'
      path: '/$username/collection'
      fullPath: '/$username/collection'
      preLoaderRoute: typeof UsernameCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/settings/': {
      id: '/$username/settings/'
      path: '/$username/settings'
      fullPath: '/$username/settings'
      preLoaderRoute: typeof UsernameSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/settings/connections': {
      id: '/$username/settings/connections'
      path: '/$username/settings/connections'
      fullPath: '/$username/settings/connections'
      preLoaderRoute: typeof UsernameSettingsConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/external/youtube/search': {
      id: '/api/external/youtube/search'
      path: '/api/external/youtube/search'
      fullPath: '/api/external/youtube/search'
      preLoaderRoute: typeof ApiExternalYoutubeSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/external/youtube/$videoId': {
      id: '/api/external/youtube/$videoId'
      path: '/api/external/youtube/$videoId'
      fullPath: '/api/external/youtube/$videoId'
      preLoaderRoute: typeof ApiExternalYoutubeVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/external/discogs/search': {
      id: '/api/external/discogs/search'
      path: '/api/external/discogs/search'
      fullPath: '/api/external/discogs/search'
      preLoaderRoute: typeof ApiExternalDiscogsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/external/discogs/collection': {
      id: '/api/external/discogs/collection'
      path: '/api/external/discogs/collection'
      fullPath: '/api/external/discogs/collection'
      preLoaderRoute: typeof ApiExternalDiscogsCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discogs/status': {
      id: '/api/auth/discogs/status'
      path: '/api/auth/discogs/status'
      fullPath: '/api/auth/discogs/status'
      preLoaderRoute: typeof ApiAuthDiscogsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discogs/request-token': {
      id: '/api/auth/discogs/request-token'
      path: '/api/auth/discogs/request-token'
      fullPath: '/api/auth/discogs/request-token'
      preLoaderRoute: typeof ApiAuthDiscogsRequestTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discogs/disconnect': {
      id: '/api/auth/discogs/disconnect'
      path: '/api/auth/discogs/disconnect'
      fullPath: '/api/auth/discogs/disconnect'
      preLoaderRoute: typeof ApiAuthDiscogsDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discogs/callback': {
      id: '/api/auth/discogs/callback'
      path: '/api/auth/discogs/callback'
      fullPath: '/api/auth/discogs/callback'
      preLoaderRoute: typeof ApiAuthDiscogsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/external/discogs/release/$id': {
      id: '/api/external/discogs/release/$id'
      path: '/api/external/discogs/release/$id'
      fullPath: '/api/external/discogs/release/$id'
      preLoaderRoute: typeof ApiExternalDiscogsReleaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnalyzeRouteChildren {
  AnalyzeChatRoute: typeof AnalyzeChatRoute
}

const AnalyzeRouteChildren: AnalyzeRouteChildren = {
  AnalyzeChatRoute: AnalyzeChatRoute,
}

const AnalyzeRouteWithChildren =
  AnalyzeRoute._addFileChildren(AnalyzeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRouteWithChildren,
  WaitlistRoute: WaitlistRoute,
  UsernameCollectionRoute: UsernameCollectionRoute,
  UsernamePlaylistsRoute: UsernamePlaylistsRoute,
  UsernameTracksRoute: UsernameTracksRoute,
  OnboardingConnectRoute: OnboardingConnectRoute,
  UsernameIndexRoute: UsernameIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  UsernameSettingsConnectionsRoute: UsernameSettingsConnectionsRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  UsernameSettingsIndexRoute: UsernameSettingsIndexRoute,
  ApiAuthDiscogsCallbackRoute: ApiAuthDiscogsCallbackRoute,
  ApiAuthDiscogsDisconnectRoute: ApiAuthDiscogsDisconnectRoute,
  ApiAuthDiscogsRequestTokenRoute: ApiAuthDiscogsRequestTokenRoute,
  ApiAuthDiscogsStatusRoute: ApiAuthDiscogsStatusRoute,
  ApiExternalDiscogsCollectionRoute: ApiExternalDiscogsCollectionRoute,
  ApiExternalDiscogsSearchRoute: ApiExternalDiscogsSearchRoute,
  ApiExternalYoutubeVideoIdRoute: ApiExternalYoutubeVideoIdRoute,
  ApiExternalYoutubeSearchRoute: ApiExternalYoutubeSearchRoute,
  ApiExternalDiscogsReleaseIdRoute: ApiExternalDiscogsReleaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
